export default {
  HEIGHT: 66,
  BLUR_ANIMATION_DURATION: 180,
  FOCUS_ANIMATION_DURATION: 180,
  BLUR_COLOR: '#78849D',
  FOCUS_COLOR: '#0A94FF',
  ERROR_COLOR: '#FD3E3E',
  TEXTINPUT_FONTSIZE: 17,
  BLUR_LABEL_FONTSIZE: 17,
  FOCUS_LABEL_FONTSIZE: 12,
  SPACING: 14,
  LABEL_TOP_POSITION: 5,
}