//
//  Images.js:
//  BoilerPlate
//
//  Created by Retrocube on 10/4/2019, 9:46:34 AM.
//  Copyright © 2019 Retrocube. All rights reserved.
//
export default {
   // =============================================================================
   // NAVIGATION
   // =============================================================================
   icBack: require('../assets/images/navigation/icBack.png'),
   icMenu: require('../assets/images/navigation/icMenu.png'),
   Home: require('../assets/images/navigation/Home.png'),
   Search: require('../assets/images/navigation/Search.png'),
   Chat: require('../assets/images/navigation/Chat.png'),
   Notifications: require('../assets/images/navigation/Notifications.png'),
   Profile: require('../assets/images/navigation/Profile.png'),
   Tokens: require('../assets/images/navigation/Tokens.png'),
   PostModal: require('../assets/images/navigation/PostModal.png'),
   // =============================================================================
   // APP
   // =============================================================================
   usertype: require('../assets/images/usertype.png'),
   bgLogin: require('../assets/images/bgLogin.png'),
   bg: require('../assets/images/bg.png'),
   icFb: require('../assets/images/icFb.png'),
   icGoogle: require('../assets/images/icGoogle.png'),
   icApple: require('../assets/images/icApple.png'),
   icEye: require('../assets/images/icEye.png'),
   icEyeSecure: require('../assets/images/icEyeSecure.png'),
   icTickGrey: require('../assets/images/icTickGrey.png'),
   pickerPlaceholder: require('../assets/images/pickerPlaceholder.png'),
   icFacebook: require('../assets/images/icFacebook.png'),
   icInstagram: require('../assets/images/icInstagram.png'),
   icTwitter: require('../assets/images/icTwitter.png'),
   icYoutube: require('../assets/images/icYoutube.png'),
   icSnapchat: require('../assets/images/icSnapchat.png'),
   icWeblink: require('../assets/images/icWeblink.png'),
   icSearch: require('../assets/images/icSearch.png'),
   icSave: require('../assets/images/icSave.png'),
   icSearchWithBg: require('../assets/images/icSearchWithBg.png'),
   icEditBlue: require('../assets/images/icEditBlue.png'),
   icSettings: require('../assets/images/icSettings.png'),
   icVerticalDots: require('../assets/images/icVerticalDots.png'),
   bgFade: require('../assets/images/bgFade.png'),
   icLiked: require('../assets/images/icLiked.png'),
   icUnliked: require('../assets/images/icUnLiked.png'),
   icDisliked: require('../assets/images/icDisliked.png'),
   icUnDisliked: require('../assets/images/icUnDisliked.png'),
   icComment: require('../assets/images/icComment.png'),
   icToken: require('../assets/images/icToken.png'),
   icUnselected: require('../assets/images/icUnselected.png'),
   icSelected: require('../assets/images/icSelected.png'),
   icAudio: require('../assets/images/icAudio.png'),
   icVideo: require('../assets/images/icVideo.png'),
   icPost: require('../assets/images/icPost.png'),
   icPlus: require('../assets/images/icPlus.png'),
   icChevronsRight: require('../assets/images/icChevronsRight.png'),
   icLocation: require('../assets/images/icLocation.png'),
   icCross: require('../assets/images/icCross.png'),
   coins: require('../assets/images/coins.png'),
   icDollar: require('../assets/images/icDollar.png'),
   icDotsSeparator: require('../assets/images/icDotsSeparator.png'),
   icGrid: require('../assets/images/icGrid.png'),
   icTagPerson: require('../assets/images/icTagPerson.png'),
   icFollowRequest: require('../assets/images/icFollowRequest.png'),
   icCalendar: require('../assets/images/icCalendar.png'),
   icForward: require('../assets/images/icForward.png'),
   icDown: require('../assets/images/icDown.png'),
   bgFaq: require('../assets/images/bgFaq.png'),
   icSendMessage: require('../assets/images/icSendMessage.png'),
   icAttachment: require('../assets/images/icAttachment.png'),
   bgTokenScreen: require('../assets/images/bgTokenScreen.png'),
   tokenCard: require('../assets/images/tokenCard.png'),
   tokenCoins: require('../assets/images/tokenCoins.png'),
   blurToken: require('../assets/images/blurToken.png'),
   supportCoin: require('../assets/images/supportCoin.png'),
   buyToken: require('../assets/images/buyToken.png'),
   tokenBg: require('../assets/images/tokenBg.png'),
   icChevron: require('../assets/images/icChevron.png'),
   icUploadFinish: require('../assets/images/icUploadFinish.png'),
   icPickAudio: require('../assets/images/icPickAudio.png'),
   icVideoRecorder: require('../assets/images/icVideoRecorder.png'),
   icSend: require('../assets/images/icSend.png'),
   icPromote: require('../assets/images/icPromote.png'),
   icCollab: require('../assets/images/icCollab.png'),

   // =============================================================================
   // VIDEO
   // =============================================================================
   icVolume: require('../assets/images/video/icVolume.png'),
   icRewind: require('../assets/images/video/icRewind.png'),
   icPlay: require('../assets/images/video/icPlay.png'),
   icPause: require('../assets/images/video/icPause.png'),
   icFastForward: require('../assets/images/video/icFastForward.png'),
   icFullscreen: require('../assets/images/video/icFullscreen.png'),
   icMute: require('../assets/images/video/icMute.png'),

   // =============================================================================
   // AUDIO
   // =============================================================================
   icAudioPlay: require('../assets/images/audio/icAudioPlay.png'),
   icAudioPause: require('../assets/images/audio/icAudioPause.png'),
   icAudioThumb: require('../assets/images/audio/icAudioThumb.png'),

   // =============================================================================
   // EXTRA
   // =============================================================================
   imgMusician: require('../assets/images/extra/imgMusician.png'),
   imgMusicProducer: require('../assets/images/extra/imgMusicProducer.png'),
   imgSongWirter: require('../assets/images/extra/imgSongWirter.png'),
   imgVideoEditor: require('../assets/images/extra/imgVideoEditor.png'),
   imgVideoDirector: require('../assets/images/extra/imgVideoDirector.png'),
   imgBookingHiringAgent: require('../assets/images/extra/imgBookingHiringAgent.png'),
};
