const INPUT_TYPES = {
   TEXT: 'TEXT',
   EMAIL: 'EMAIL',
   PASSWORD: 'PASSWORD',
   CONFIRM_PASSWORD: 'CONFIRM_PASSWORD',
   NUMBER: 'NUMBER',
   DECIMAL: 'DECIMAL',
   PHONE: 'PHONE',
   OPTIONAL: 'OPTIONAL',
   SELECTABLE: 'SELECTABLE',
   DATETIME: 'DATETIME',
   GOOGLE_PLACES: 'GOOGLE_PLACES',
   PHONE_OPTIONAL: 'PHONE_OPTIONAL'
};

export { INPUT_TYPES }